# Generated by Django 5.1.1 on 2024-09-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_registration',
            name='turf_id',
            field=models.CharField(default='00000000000000000', max_length=20, unique=True),
        ),
    ]
