# Generated by Django 5.1.1 on 2024-09-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0004_alter_turf_registration_turf_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf_registration',
            old_name='turf_id',
            new_name='turf_ids',
        ),
    ]
