# Generated by Django 5.1.1 on 2024-09-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0005_rename_turf_id_turf_registration_turf_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_registration',
            name='turf_ids',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
