# Generated by Django 5.1.1 on 2024-09-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turfs", "0006_alter_turf_registration_turf_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="turf_registration",
            name="turf_end_time",
            field=models.CharField(default="12 P.M", max_length=10),
        ),
        migrations.AddField(
            model_name="turf_registration",
            name="turf_start_time",
            field=models.CharField(default="6 A.M", max_length=10),
        ),
    ]
