# Generated by Django 5.1.1 on 2024-10-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0007_turf_registration_turf_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_turf_mobile_number',
            fields=[
                ('user_name', models.CharField(max_length=20)),
                ('new_mobile_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=6)),
                ('isvalid', models.CharField(default='True', max_length=10)),
            ],
        ),
    ]
