# Generated by Django 5.1.1 on 2024-10-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turfs", "0008_update_turf_mobile_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turf_bank_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turf_id", models.CharField(max_length=50)),
                ("bank_account_number", models.CharField(max_length=30)),
                ("ifsc_code", models.CharField(max_length=20)),
                ("rpay_vir_account_number", models.CharField(max_length=30)),
            ],
        ),
    ]
