# Generated by Django 5.1.1 on 2024-10-22 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Live_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=100)),
                ('saved_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('saved_by', models.CharField(max_length=20)),
                ('active_status', models.CharField(default='YES', max_length=3)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('saved_by', 'ADMIN')), name='saved_by_check2')],
            },
        ),
        migrations.CreateModel(
            name='Test_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=100)),
                ('saved_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('saved_by', models.CharField(max_length=20)),
                ('active_status', models.CharField(default='YES', max_length=3)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('saved_by', 'ADMIN')), name='saved_by_check1')],
            },
        ),
    ]
