# Generated by Django 5.1.1 on 2024-09-13 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_signup",
            fields=[
                ("name", models.CharField(max_length=50)),
                (
                    "mobile_number",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("mailid", models.EmailField(max_length=50, unique=True)),
                ("user_name", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=128)),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
