# Generated by Django 5.1.1 on 2024-09-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_mobile_number_random_token_generation_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forget_user_password',
            fields=[
                ('user_name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mailid', models.EmailField(max_length=50, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('isvalid', models.CharField(default='False', max_length=10)),
            ],
        ),
    ]
