# Generated by Django 5.1.1 on 2024-10-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_id", models.CharField(max_length=20, unique=True)),
                ("turf_id", models.CharField(max_length=20)),
                ("booking_date_time", models.DateField()),
                ("slot_start_date_time", models.DateField()),
                ("slot_end_date_time", models.DateField()),
                ("user_id", models.CharField(max_length=20)),
                ("user_mobile_number", models.CharField(max_length=10)),
                ("amount", models.CharField(max_length=10)),
                ("payment_status", models.CharField(default="pending", max_length=20)),
                ("temp_lock", models.CharField(default="LOCKED", max_length=10)),
            ],
        ),
    ]
